server:
  port: 9002
  servlet:
    context-path: "/lamp/atom/service/operator"

spring:
  application:
    name: atom-space-operator-consumer
  datasource:
    name: lamp
    url: jdbc:mysql://120.78.148.188:3306/atom?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: lampup
    password: Lampup@123
    # using druid data source
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # encrypt password
    filters: config

nacos:
  config:
    bootstrap:
      enable: true
      logEnable: true
    server-addr: 127.0.0.1:8848
    namespace: atom
    remote-first: true
    type: yaml
    auto-refresh: true
    max-retry: 10
    config-retry-time: 2333
    config-long-poll-timeout: 46000
    enable-remote-sync-config: true

mybatis:
  checkConfig-location : false
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql